name: marlin_auto_build

on:
  # trigger if we change a build
  push:
    branches: [ "main" ]
    
jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: zisismaras/marlin_auto_build@master
